<?php
session_start();
include __DIR__ . '/../includes/db.php';

// Only Admin Access
if (!isset($_SESSION['user_id']) || $_SESSION['role_id'] != 2) {
    header("Location: ../login.php");
    exit();
}

// Get Admin Info
$admin_id = $_SESSION['user_id'];
$stmtAdmin = $pdo->prepare("SELECT * FROM users WHERE U_Id = ?");
$stmtAdmin->execute([$admin_id]);
$admin = $stmtAdmin->fetch();

// Filters
$from = $_GET['from'] ?? null;
$to = $_GET['to'] ?? null;
$status = $_GET['status'] ?? null;

// Base Query
$query = "SELECT c.*, u.F_name AS citizen_name, a.F_name AS assigned_name
          FROM complaint c
          LEFT JOIN users u ON c.U_Id = u.U_Id
          LEFT JOIN users a ON c.Assigned_To = a.U_Id
          WHERE 1=1";

// Apply Filters
$params = [];

if ($status && $status != "All") {
    $query .= " AND c.Status = ?";
    $params[] = $status;
}

// Execute Query
$stmt = $pdo->prepare($query);
$stmt->execute($params);
$complaints = $stmt->fetchAll();

// Summary Counts
$total = $pdo->query("SELECT COUNT(*) FROM complaint")->fetchColumn();
$pending = $pdo->query("SELECT COUNT(*) FROM complaint WHERE Status='Pending'")->fetchColumn();
$resolved = $pdo->query("SELECT COUNT(*) FROM complaint WHERE Status='Resolved'")->fetchColumn();
$escalated = $pdo->query("SELECT COUNT(*) FROM complaint WHERE Status='Escalated'")->fetchColumn();

// Severity Count
$severityData = $pdo->query("
    SELECT Severity, COUNT(*) as total 
    FROM complaint 
    GROUP BY Severity
")->fetchAll();

// Authority Count
$authorityData = $pdo->query("
    SELECT r.R_Name, COUNT(*) as total
    FROM complaint c
    JOIN users u ON c.Assigned_To = u.U_Id
    JOIN role r ON u.Role_Id = r.R_Id
    GROUP BY r.R_Name
")->fetchAll();
?>

<!DOCTYPE html>
<html>
<head>
    <title>Admin Report</title>
    <link rel="stylesheet" href="../css/report.css">
</head>

<body>
    <?php include 'admin_header.php'; ?>

<div class="container">

    <h1> EcoGuard Admin Report</h1>
    <p style="text-align:center;">
        Generated by: <b><?php echo $admin['F_name']; ?></b> |
        Date: <?php echo date("Y-m-d"); ?>
    </p>

    <!-- FILTERS -->
    <div class="box filters">
        <form method="GET">
            <label>Status:</label>
            <select name="status">
                <option>All</option>
                <option>Pending</option>
                <option>Resolved</option>
                <option>Escalated</option>
            </select>

            <button class="btn">Generate</button>
            <button type="button" class="btn" onclick="window.print()">Print</button>
        </form>
    </div>

    <!-- SUMMARY -->
    <div class="box flex">
        <div class="card">
            <h3>Total</h3>
            <p><?php echo $total; ?></p>
        </div>
        <div class="card">
            <h3>Pending</h3>
            <p><?php echo $pending; ?></p>
        </div>
        <div class="card">
            <h3>Resolved</h3>
            <p><?php echo $resolved; ?></p>
        </div>
        <div class="card">
            <h3>Escalated</h3>
            <p><?php echo $escalated; ?></p>
        </div>
    </div>

    <!-- SEVERITY -->
    <div class="box">
        <h2>Complaints by Severity</h2>
        <table>
            <tr>
                <th>Severity</th>
                <th>Total</th>
            </tr>
            <?php foreach ($severityData as $row): ?>
                <tr>
                    <td><?php echo $row['Severity']; ?></td>
                    <td><?php echo $row['total']; ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>

    <!-- AUTHORITY -->
    <div class="box">
        <h2>Complaints by Authority</h2>
        <table>
            <tr>
                <th>Authority</th>
                <th>Total</th>
            </tr>
            <?php foreach ($authorityData as $row): ?>
                <tr>
                    <td><?php echo $row['R_Name']; ?></td>
                    <td><?php echo $row['total']; ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>

    <!-- DETAILS -->
    <div class="box">
        <h2>Detailed Complaints</h2>
        <table>
            <tr>
                <th>ID</th>
                <th>Location</th>
                <th>Severity</th>
                <th>Status</th>
                <th>Assigned To</th>
                <th>Citizen</th>
            </tr>
            <?php foreach ($complaints as $c): ?>
                <tr>
                    <td><?php echo $c['C_Id']; ?></td>
                    <td><?php echo $c['Location']; ?></td>
                    <td><?php echo $c['Severity']; ?></td>
                    <td><?php echo $c['Status']; ?></td>
                    <td><?php echo $c['assigned_name'] ?? '-'; ?></td>
                    <td><?php echo $c['citizen_name']; ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>

</div>

<?php include 'admin_footer.php'; ?>
</body>
</html>